inference:
  module: 'custom_model.load_classifier'
  label_map: 'resources/imagenet_mapping.json'
  class: 'LoadClassifier'
  output_shape: [1000]
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  resolution: [224, 224]
  args:
      output_dim: 1000
      path_to_model: './unit_tests/load_model/resnet18.pth'
evaluation:
  module: 'threedb.evaluators.classification'
  args:
    classmap_path: 'resources/ycb_to_IN.json'
    topk: 1
render_args:
  engine: 'threedb.rendering.render_blender'
  resolution: 256
  samples: 16
policy:
  module: "threedb.policies.grid_search"
  samples_per_dim: 1
logging:
  logger_modules:
    - "threedb.result_logging.image_logger"
    - "threedb.result_logging.json_logger"
